---
Name: lazycoders-elemental
After:
  - '#elemental'
---

SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - lazycoders/silverstripe-elemental-kit

DNADesign\Elemental\Extensions\ElementalAreasExtension:
  keep_content_fields: true
