---
Name: lazycoders-elemental
After:
  - '#elemental'
---

SilverStripe\Core\Manifest\ModuleManifest:
  module_priority:
    - lazycoders/silverstripe-elemental-kit


Page:
  extensions:
    - DNADesign\Elemental\Extensions\ElementalPageExtension
  disallowed_elements:
    - DNADesign\Elemental\Models\ElementContent
    - LazyCoders\Elemental\CoreElement

DNADesign\Elemental\Extensions\ElementalAreasExtension:
  keep_content_fields: true
